// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.startupRolloutPrefs.doh-rollout.enabled", true);
user_pref("app.normandy.startupRolloutPrefs.doh-rollout.profileCreationThreshold", "1896163212345");
user_pref("app.normandy.startupRolloutPrefs.doh-rollout.provider-steering.enabled", true);
user_pref("app.normandy.startupRolloutPrefs.doh-rollout.provider-steering.provider-list", "[{ \"name\": \"comcast\", \"canonicalName\": \"doh-discovery.xfinity.com\", \"uri\": \"https://doh.xfinity.com/dns-query\" }]");
user_pref("app.normandy.user_id", "5f2b4f3b-9d2a-4644-abdc-823461879d05");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1610751056);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1610751123);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1610751034);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1610751176);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1610751085);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1610751025);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 104);
user_pref("browser.newtabpage.activity-stream.impressionId", "{3b603041-63e4-40cf-9c67-a313bea18c32}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1610751067677");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1610752865677");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1610751037658");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1610772637658");
user_pref("browser.search.region", "US");
user_pref("browser.slowStartup.averageTime", 11177);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20210105180113");
user_pref("browser.startup.homepage_override.mstone", "84.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1610751030);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1610751033899");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "84.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.mode", 2);
user_pref("doh-rollout.self-enabled", true);
user_pref("dom.push.userAgentID", "d7370dfdb2de4f8b86e0068e2cab15e9");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "84.0.2");
user_pref("extensions.lastPlatformVersion", "84.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_picture_in_picture_overrides", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"be474627-22de-4956-bc5e-b96ff946bb85\",\"formautofill@mozilla.org\":\"99c96634-7636-4e94-87af-d1268007092e\",\"screenshots@mozilla.org\":\"b8df3d74-d513-4b87-9a94-3a5cdcb9ebba\",\"webcompat-reporter@mozilla.org\":\"03b6172b-3300-4478-aa81-b0f262b9a271\",\"webcompat@mozilla.org\":\"a3e1b5ca-93c8-497b-a41a-440b0773e20e\",\"default-theme@mozilla.org\":\"49571204-9d12-41b6-89a6-16f85b63d813\",\"google@search.mozilla.org\":\"ff3f981f-d806-4157-bb98-f85a91337a2c\",\"amazondotcom@search.mozilla.org\":\"d6e96661-1f34-4e98-9ce2-1bd1c6389bff\",\"wikipedia@search.mozilla.org\":\"a80caa36-b664-4cb5-b597-56e2602d12df\",\"bing@search.mozilla.org\":\"83291586-c8eb-4476-b3cb-ee3d7d1296ca\",\"ddg@search.mozilla.org\":\"a493e401-e87f-444b-9b07-46ab7be1d5c6\",\"ebay@search.mozilla.org\":\"4a9e10ae-0dac-414d-a08c-fc58a4075265\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "1a84caf2-2d07-4e51-96dd-e0e201aa62e0");
user_pref("security.sandbox.plugin.tempDirSuffix", "6298d375-9e72-482c-9ec1-ca97d37f4c3e");
user_pref("toolkit.startup.last_success", 1610751019);
user_pref("toolkit.telemetry.cachedClientID", "ebea2ed5-951d-4078-9b92-2ca2d528e9d4");
user_pref("toolkit.telemetry.previousBuildID", "20210105180113");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
